#!/usr/bin/env bash
# Installs nginx on the server
# Nginx set to listen on port 80
# Nginx to return a page that contains the string "Hello World!"
#  when queried at its root / with a GET request using curl.
# "systemctl" not allowed for restarting of nginx.


#Update package list
apt-get update

#install nginx
apt-get install -y nginx


#Ensure nginx is listening on port 80
ufw allow 'Nginx HTTP'

#Create HTML file to display string in the root directory
echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html


#Reload nginx without using systemctl
nginx -s reload
