#!/usr/bin/env bash
# Configures an nginx server so that /redirect-me is redirecting to another page.
# The redirection is a 301 Moved permanently.

#Update package list
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

#Ensure nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

#Create HTML file to display string in the root directory
sudo cho "<html><body><h1>Hello World!</h1></body></html>" > | sudo tee /var/www/html/index.html > /dev/null

# Replace the location / block or add a new block for /redirect_me
sudo sed -i '/index index.html;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\n\t}' /etc/nginx/sites-available/default

#Reload nginx without using systemctl
sudo service nginx restart
