#!/usr/bin/env bash
# Configures an nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# The page must return an HTTP 404 error code.

#Update package list
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

#Ensure nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

#Create HTML file to display string in the root directory
sudo echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Create HTML file to display error message
sudo echo "<html><body><h1>Ceci n'est pas une page</h1></body></html>" | sudo tee /var/www/html/custom_404.html > /dev/null

# Create or update location blocks
sudo echo "server {
		listen 80 default_server;
		listen [::]:80 default_server;


		root /var/www/html;
		index index.html;


		location /redirect_me {
			return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
		}


		# Error page configuration
		error_page 404 /custom_404.html;
		location = /custom_404.html {
			internal;
		}


		location / {
			try_files \$uri \$uri/ =404;
		}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

#Reload nginx without using systemctl
sudo service nginx restart
