#!/usr/bin/env bash
#A script that displays a list of currently running processes
#for all users, including those which do not have a TTY
#displayed in a User-oriented format, showing process hierarchy.

ps -auxf
