#!/usr/bin/env bash
# Creates an RSA key pair
# Name of the created private key must be school
# Number of bits in the created key 4096
# Created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -N "betty" -f school
